import Image from "next/image";

import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { images } from "./data";

export function BeneficiarySection() {
  return <section className="w-full bg-white py-16 lg:py-20"><div className="mx-auto max-w-[1200px] px-6"><Card className="grid items-center gap-8 rounded-3xl bg-[var(--surface-muted)] p-8 shadow-sm sm:p-12 lg:grid-cols-12 lg:gap-12 lg:p-16"><div className="flex flex-col gap-6 lg:col-span-7"><Badge className="self-start bg-[#fff4ed] text-[#b43826]">♥ Voice from the Ground</Badge><div><span className="text-xs font-bold uppercase tracking-wider text-[#b43826]">Apprenticeship Spotlight</span><h3 className="mt-2 text-3xl font-bold tracking-tight">Amina&apos;s Journey: From Uncertainty to Master Garment Artisan</h3></div><blockquote className="border-l-4 border-[#b43826] pl-4 text-lg italic leading-8 text-slate-700">“Before YDI opened the tailoring pod in Nansana, I couldn&apos;t afford secondary fees and had little hope for steady work. Today, I earn a daily income repairing and crafting school uniforms for children in my neighbourhood.”</blockquote><div className="grid grid-cols-3 gap-3"><Card className="rounded-2xl bg-white p-4"><b className="block text-lg text-[#0284c7]">6 Mos</b><span className="text-xs text-slate-600">Hands-on Training</span></Card><Card className="rounded-2xl bg-white p-4"><b className="block text-lg text-emerald-600">100%</b><span className="text-xs text-slate-600">Starter Kit Funded</span></Card><Card className="rounded-2xl bg-white p-4"><b className="block text-lg text-purple-700">2 Mothers</b><span className="text-xs text-slate-600">Mentored Locally</span></Card></div></div><div className="relative lg:col-span-5"><div className="relative h-[400px] overflow-hidden rounded-3xl shadow-xl"><Image className="object-cover" src={images.amina} fill sizes="(min-width: 1024px) 42vw, 100vw" alt="Amina tailoring at her sewing machine" /><div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent" /><div className="absolute left-4 right-4 top-4"><Badge className="bg-white/90 text-slate-800">● Direct Field Audio Recording</Badge></div><div className="absolute bottom-4 left-4 right-4 rounded-2xl bg-white/95 p-3 shadow-lg"><b className="block text-sm">▶ Listen to Amina&apos;s Voice Note</b><span className="text-xs text-slate-500">Recorded on-site in Nansana · 1m 24s</span></div></div></div></Card></div></section>;
}
