import { Card } from "@/components/ui/card";
import { MaterialIcon } from "./material-icon";

export function InvolvementSection() {
  const pathways = [
    { icon: "volunteer_activism", iconClass: "bg-[#e0f2fe] text-[#0284c7]", title: "Direct Monetary Giving", text: "Make a one-time or recurring gift supporting tuition sponsorships, clinic health camps, and apprenticeships without intermediaries.", points: ["Transparent fund allocation", "Tax-deductible receipt provided"], action: "Make a Donation", href: "#donate", button: "bg-gradient-to-r from-[#0284c7] to-[#2563eb] text-white" },
    { icon: "handyman", iconClass: "bg-[#fef3c7] text-[#d97706]", title: "In-Kind Equipment & Tools", text: "Supply functioning sewing machines, woodworking tools, welding goggles, books, and laptops to equip training centers.", points: ["Direct delivery to Wakiso pod", "Institutional shipping assistance"], action: "Donate Tools & Kits", href: "mailto:yinitiative24@gmail.com?subject=In-Kind%20Tool%20Donation", button: "bg-[#fe932c] text-white" },
    { icon: "groups", iconClass: "bg-[#d1fae5] text-[#059669]", title: "Volunteer & CSR Mentorship", text: "Connect your company, university, or artisan guild with our teams in Uganda for skill-sharing, joint grants, and volunteering.", points: ["Custom corporate partnership scope", "On-the-ground volunteer opportunities"], action: "Become a Partner", href: "#involved", button: "border border-[#c4c5d7] bg-[var(--surface-blue)] text-[#0037b0]" },
  ];
  return <section id="involved" className="w-full bg-[var(--surface-muted)] py-16 lg:py-20"><div className="mx-auto max-w-[1200px] px-6"><div className="mx-auto mb-12 max-w-2xl text-center"><span className="text-xs font-bold uppercase tracking-widest text-[#0284c7]">Join the Movement</span><h2 className="mt-2 text-[28px] font-bold leading-9 tracking-tight">Ways to Get Involved</h2><p className="mt-3 text-slate-600">Choose how you want to stand with Ugandan youth and power sustainable grassroots self-reliance.</p></div><div className="grid gap-8 md:grid-cols-3">{pathways.map((pathway) => <Card key={pathway.title} className="flex flex-col justify-between rounded-3xl p-8 shadow-sm transition-shadow hover:shadow-md"><div><div className={`mb-6 grid size-14 place-items-center rounded-2xl ${pathway.iconClass}`}><MaterialIcon name={pathway.icon} className="text-[28px]" filled /></div><h3 className="mb-3 text-xl font-semibold">{pathway.title}</h3><p className="mb-6 leading-7 text-slate-600">{pathway.text}</p><ul className="mb-6 space-y-2 text-sm text-slate-600">{pathway.points.map((point) => <li className="flex items-center gap-2" key={point}><MaterialIcon name="check" className="text-base text-[#0284c7]" />{point}</li>)}</ul></div><a href={pathway.href} className={`flex items-center justify-center gap-2 rounded-xl px-4 py-3.5 text-center text-sm font-semibold shadow-md transition-all hover:opacity-95 ${pathway.button}`}>{pathway.action}<MaterialIcon name="arrow_forward" className="text-base" /></a></Card>)}</div><Card className="mt-12 flex flex-col items-start justify-between gap-6 rounded-3xl bg-[var(--surface)] p-8 shadow-sm md:flex-row md:items-center"><div className="flex items-start gap-4 md:items-center"><div className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#e0f2fe] text-[#0284c7]"><MaterialIcon name="contact_support" className="text-[26px]" /></div><div><h4 className="text-lg font-semibold">Have a custom partnership idea or want to visit our field team?</h4><p className="mt-1 text-sm leading-5 text-slate-600">Reach out directly to our volunteer and partnership coordinator to design tailored initiatives or schedule an on-site visit in Nansana.</p></div></div><div className="flex w-full flex-wrap gap-3 md:w-auto"><a href="#involved" className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#0284c7] px-6 py-3 text-sm font-semibold text-white shadow sm:w-auto">Get In Touch <MaterialIcon name="arrow_forward" className="text-base" /></a><a href="mailto:yinitiative24@gmail.com?subject=Field%20Visit%20or%20Custom%20Collaboration" className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-[#c4c5d7] bg-[var(--surface-blue)] px-5 py-3 text-sm font-semibold text-[#0037b0] sm:w-auto"><MaterialIcon name="mail" className="text-base" />Email Coordinator</a></div></Card></div></section>;
}
