import Image from "next/image";

import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { pillars } from "./data";
import { MaterialIcon } from "./material-icon";
import { SectionHeading } from "./section-heading";

export function ProgramsSection() {
  return <section id="programs" className="w-full py-16 lg:py-24"><div className="mx-auto max-w-[1200px] px-6"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><SectionHeading eyebrow="Core Impact Pillars" title="Integrated Community Programs"><p className="mt-3 max-w-xl text-slate-600">Targeting root bottlenecks to empower the whole community — from classroom scholastic materials to daily nutrition and clean living.</p></SectionHeading><a className="mb-12 inline-flex items-center gap-2 text-sm font-semibold text-[#0284c7] transition-colors hover:text-[#0037b0]" href="#programs">Explore all ongoing work <MaterialIcon name="east" className="text-lg" /></a></div><div className="grid gap-8 md:grid-cols-3">{pillars.map(([title, location, locationTone, icon, image, text, points, tone], index) => { const styles = tone === "green" ? { badge: "bg-[#d1fae5] text-[#047857]", check: "text-[#059669]", dot: "bg-[#006948]" } : { badge: "bg-[#e0f2fe] text-[#0284c7]", check: "text-[#0284c7]", dot: locationTone === "secondary" ? "bg-[#fe932c]" : "bg-[#0037b0]" }; return <Card key={title} className="group flex flex-col overflow-hidden rounded-3xl bg-[#eaedff] p-0 shadow-sm transition-colors hover:bg-[#e2e7ff]"><div className="relative h-60 overflow-hidden"><Image className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" src={image} fill sizes="(min-width: 768px) 33vw, 100vw" alt={title} /><Badge className="absolute left-3 top-3 inline-flex items-center gap-1.5 rounded-full bg-white/90 text-slate-800 shadow-sm backdrop-blur-md"><span className={`size-2 rounded-full ${styles.dot}`} />{location}</Badge></div><div className="flex flex-1 flex-col gap-4 p-6 lg:p-8"><Badge className={`inline-flex items-center gap-1.5 self-start ${styles.badge}`}><MaterialIcon name={icon} className="text-sm" filled={index === 1 || index === 2} />Pillar 0{index + 1}</Badge><h3 className="text-xl font-semibold">{title}</h3><p className="text-base leading-6 text-slate-600">{text}</p><ul className="mt-auto space-y-2 pt-2 text-sm text-slate-600">{points.map((point) => <li key={point} className="flex items-center gap-2"><MaterialIcon name="check_circle" className={`text-base ${styles.check}`} /><span>{point}</span></li>)}</ul></div></Card>; })}</div></div></section>;
};
