import Image from "next/image";
import { Badge } from "@/components/ui/badge";

import { Card } from "@/components/ui/card";
import { trades } from "./data";
import { MaterialIcon } from "./material-icon";

export function VocationalSection() {
  return <section className="w-full bg-[#101828] py-16 text-white lg:py-24"><div className="mx-auto max-w-[1200px] px-6"><div className="mb-12 flex max-w-xl flex-col gap-2"><span className="flex items-center gap-1.5 text-xs font-extrabold uppercase tracking-widest text-sky-400"><span className="size-2 rounded-full bg-[#fe932c]" />Livelihood Pathways</span><h2 className="text-[28px] font-extrabold tracking-tight text-white">Vocational Apprenticeship in Action</h2><p className="text-base leading-6 text-slate-300">Practical mastery turns reliance into independence. We provide tangible technical training that equips young Ugandans with competitive, tradeable skills.</p></div><div className="grid gap-8 md:grid-cols-3">{trades.map(([title, label, icon, iconTone, location, badge, image, text]) => { const styles = iconTone === "purple" ? { text: "text-sky-400", dot: "bg-sky-400", badge: "bg-sky-500" } : iconTone === "blue" ? { text: "text-cyan-400", dot: "bg-cyan-400", badge: "bg-cyan-600" } : { text: "text-[#fe932c]", dot: "bg-[#fe932c]", badge: "bg-[#fe932c]" }; return <Card key={title} className="group flex flex-col overflow-hidden rounded-3xl border border-slate-700 bg-[#1d2939] p-0 text-white shadow-xl transition-all hover:border-sky-400"><div className="relative h-60 overflow-hidden"><Image className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" src={image} fill sizes="(min-width: 768px) 33vw, 100vw" alt={title} /><div className="absolute inset-0 bg-gradient-to-t from-[#1d2939] via-transparent to-black/40" /><Badge className="absolute left-3 top-3 inline-flex items-center gap-1.5 rounded-full border border-white/20 bg-black/70 text-xs font-bold text-white backdrop-blur-md"><span className={`size-2 rounded-full ${styles.dot}`} />{location}</Badge><span className={`absolute bottom-3 right-3 rounded-full px-3 py-1 text-[11px] font-bold text-white ${styles.badge}`}>{badge}</span></div><div className="flex flex-1 flex-col gap-3 p-6 lg:p-8"><div className="flex items-center justify-between"><span className={`text-xs font-extrabold uppercase tracking-wider ${styles.text}`}>{label}</span><MaterialIcon name={icon} className={`text-xl ${styles.text}`} /></div><h3 className="text-xl font-bold text-white">{title}</h3><p className="text-base leading-relaxed text-slate-300">{text}</p></div></Card>; })}</div></div></section>;
}
