import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { trades } from "./data";
import { MaterialIcon } from "./material-icon";
import { SectionHeading } from "./section-heading";

export function VocationalSection() {
  return <section className="w-full bg-[var(--surface-muted)] py-16 lg:py-24"><div className="mx-auto max-w-[1200px] px-6"><SectionHeading eyebrow="Livelihood Pathways" title="Vocational Apprenticeship in Action"><p className="mt-3 max-w-2xl text-slate-600">Practical mastery turns reliance into independence. We provide tangible technical training that equips young Ugandans with competitive, tradeable skills.</p></SectionHeading><div className="grid gap-6 lg:gap-8 md:grid-cols-3">{trades.map(([title, label, icon, iconTone, location, badge, image, text]) => { const styles = iconTone === "purple" ? { text: "text-[#7e22ce]", dot: "bg-[#9333ea]" } : iconTone === "blue" ? { text: "text-[#0284c7]", dot: "bg-[#0037b0]" } : { text: "text-[#b45309]", dot: "bg-[#b45309]" }; return <Card key={title} className="group flex flex-col gap-4 rounded-3xl bg-[var(--surface)] p-6 shadow-sm"><div className="relative h-72 overflow-hidden rounded-2xl bg-[var(--surface-blue)]"><img className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" src={image} alt={title} /><Badge className="absolute left-3 top-3 inline-flex items-center gap-1.5 rounded-full bg-white/90 text-slate-800 shadow-sm backdrop-blur-md"><span className={`size-2 rounded-full ${styles.dot}`} />{location}</Badge><span className="absolute bottom-3 right-3 rounded-full bg-black/60 px-2.5 py-0.5 text-[11px] font-semibold text-white">{badge}</span></div><div className="flex items-center justify-between"><span className={`text-xs font-bold uppercase tracking-wider ${styles.text}`}>{label}</span><MaterialIcon name={icon} className={`text-xl ${styles.text}`} /></div><h3 className="text-xl font-semibold">{title}</h3><p className="text-sm leading-6 text-slate-600">{text}</p></Card>; })}</div></div></section>;
}
